- carp_mobile_sensing_app/README.md
- carp_mobile_sensing_app/lib/src/blocs/sensing_bloc.dart
I'm trying to get into the code a little and making small changes here and there.
> Small improvements to the code

- backends/carp_webservices/lib/carp_services/authentication_form.dart
Fixed deprecated RaisedButton in authentication form that causes issue in study app. Issue #260
> Changed to elevated button

- apps/carp_mobile_sensing_app/android/app/build.gradle
- apps/carp_mobile_sensing_app/android/app/src/main/AndroidManifest.xml
- apps/carp_mobile_sensing_app/lib/main.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/carp_backend.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/sensing_bloc.dart
- apps/carp_mobile_sensing_app/lib/src/sensing/local_study_protocol_manager.dart
- apps/carp_mobile_sensing_app/pubspec.yaml
- apps/carp_mobile_sensing_app/test/CAMS_app_test.dart
- apps/carp_mobile_sensing_app/test/caws_app_test.dart
- apps/carp_mobile_sensing_app/test/json/study_protocol_health.json
- apps/carp_mobile_sensing_app/test/json/study_protocol_participant.json
- backends/carp_backend/lib/carp_data_manager.dart
- backends/carp_backend/lib/data_stream_buffer.dart
- backends/carp_webservices/lib/carp_services/deployment_service.dart
- carp_mobile_sensing/lib/runtime/deployment_controller.dart
- packages/carp_context_package/CHANGELOG.md
- packages/carp_context_package/lib/carp_context_package.g.dart
- packages/carp_context_package/lib/src/air_quality/air_quality_probe.dart
- packages/carp_context_package/lib/src/location/location_probes.dart
- packages/carp_context_package/lib/src/location/location_services.dart
- packages/carp_context_package/lib/src/location_manager.dart
- packages/carp_context_package/lib/src/weather/weather_probe.dart
- packages/carp_context_package/pubspec.yaml
- packages/carp_health_package/lib/health_probe.dart
- packages/carp_polar_package/lib/carp_polar_package.dart
> Check of buffering locally

- backends/carp_backend/CHANGELOG.md
- backends/carp_backend/example/lib/example.dart
- backends/carp_backend/example/pubspec.yaml
- backends/carp_backend/lib/carp_backend.dart
- backends/carp_backend/lib/carp_data_manager.dart
- backends/carp_backend/lib/data_stream_buffer.dart
- backends/carp_backend/pubspec.yaml
- backends/carp_webservices/pubspec.yaml
- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/lib/data_managers/local/sqlite_data_manager.dart
- carp_mobile_sensing/lib/runtime/deployment_controller.dart
- carp_mobile_sensing/lib/runtime/device_manager.dart
- carp_mobile_sensing/lib/runtime/executors/executors.dart
- carp_mobile_sensing/pubspec.yaml
- packages/carp_polar_package/CHANGELOG.md
- packages/carp_polar_package/lib/carp_polar_package.g.dart
- packages/carp_polar_package/lib/polar_data.dart
- packages/carp_polar_package/pubspec.yaml
* better handling of device reconnection
* fixed upload error where connected device measurements were not uploaded
* misc small improvements also to docs
> Backend improvements

- carp_mobile_sensing/lib/runtime/client_manager.dart
> Request necessary permissions for `flutter_local_notifications` plugin

- carp_core/CHANGELOG.md
- carp_core/lib/carp_core.dart
- carp_core/lib/carp_core.json.dart
- carp_core/lib/common/application/devices/device_configuration.dart
- carp_core/lib/common/application/tasks.dart
- carp_core/lib/common/application/triggers.dart
- carp_core/lib/common/carp_core_common.dart
- carp_core/pubspec.yaml
- carp_core/test/carp_core_dart_test.dart
- carp_core/test/json/carp.core-dart/study_protocol.json
- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/example/ios/Flutter/AppFrameworkInfo.plist
- carp_mobile_sensing/example/ios/Runner.xcodeproj/project.pbxproj
- carp_mobile_sensing/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- carp_mobile_sensing/example/lib/example.dart
- carp_mobile_sensing/example/lib/main.dart
- carp_mobile_sensing/lib/domain/triggers.dart
- carp_mobile_sensing/lib/runtime/executors/executor_factory.dart
- carp_mobile_sensing/lib/runtime/executors/executors.dart
- carp_mobile_sensing/lib/runtime/executors/probes.dart
- carp_mobile_sensing/lib/runtime/executors/task_control_executors.dart
- carp_mobile_sensing/lib/runtime/executors/task_executors.dart
- carp_mobile_sensing/lib/runtime/executors/trigger_executors.dart
- carp_mobile_sensing/pubspec.yaml
- carp_mobile_sensing/test/cams_domain_test.dart
* automatically stopping a background task if all of its underlying probes have stopped (fix of [384](https://github.com/cph-cachet/carp.sensing-flutter/issues/384))
* upgrade to carp_core v. 1.5.0 (getting rid of `IsoDuration`)
> CAMS Release 1.5.1

- backends/carp_backend/CHANGELOG.md
- backends/carp_backend/lib/carp_data_manager.dart
- backends/carp_backend/pubspec.yaml
- packages/carp_audio_package/test/carp_media_package_test.dart
- packages/carp_connectivity_package/CHANGELOG.md
- packages/carp_connectivity_package/lib/connectivity.g.dart
- packages/carp_connectivity_package/lib/connectivity_data.dart
- packages/carp_connectivity_package/lib/connectivity_probes.dart
- packages/carp_connectivity_package/pubspec.yaml
- packages/carp_connectivity_package/test/carp_connectivity_package_test.dart
- utilities/carp_study_generator/analysis_options.yaml
- utilities/carp_study_generator/carp/carpspec.yaml
- utilities/carp_study_generator/lib/carp_study_generator.dart
- utilities/carp_study_generator/lib/cmd/command.dart
- utilities/carp_study_generator/lib/cmd/consent.dart
- utilities/carp_study_generator/lib/cmd/create.dart
- utilities/carp_study_generator/lib/cmd/delete_all_messages.dart
- utilities/carp_study_generator/lib/cmd/dry_run.dart
- utilities/carp_study_generator/lib/cmd/help.dart
- utilities/carp_study_generator/lib/cmd/localization.dart
- utilities/carp_study_generator/lib/cmd/messages.dart
- utilities/carp_study_generator/lib/cmd/update.dart
- utilities/carp_study_generator/pubspec.yaml
- utilities/carp_study_generator/test/carp_study_generator_test.dart
* study_generator updated to carp_webservices ^3.0.0 and released as 1.5.0
* carp_connectivity_package upgraded and released as 1.5.0
* carp_backend upgraded and released as 1.6.0
> Upgrade of study_generator plus packages

- apps/carp_mobile_sensing_app/lib/src/blocs/carp_backend.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/sensing.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/sensing_bloc.dart
- apps/carp_mobile_sensing_app/test/CAMS_app_test.dart
- apps/carp_mobile_sensing_app/test/caws_app_test.dart
- packages/carp_movesense_package/CHANGELOG.md
- packages/carp_movesense_package/pubspec.yaml
- packages/carp_movisens_package/CHANGELOG.md
- packages/carp_movisens_package/lib/movisens_device_manager.dart
- packages/carp_movisens_package/pubspec.yaml
- packages/carp_movisens_package/test/carp_movisens_package_test.dart
Upgrade of the CAMS demo app to the new Auth model in carp_webservices.
> Demo app upgrade

- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/lib/runtime/executors/executors.dart
- carp_mobile_sensing/pubspec.yaml
- packages/carp_connectivity_package/lib/connectivity_package.dart
- Fix of [#408](https://github.com/cph-cachet/carp.sensing-flutter/issues/408)
> Version 1.8.2

- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/LICENSE
- carp_mobile_sensing/README.md
- carp_mobile_sensing/example/android/app/build.gradle
- carp_mobile_sensing/example/android/app/src/main/AndroidManifest.xml
- carp_mobile_sensing/example/android/build.gradle
- carp_mobile_sensing/example/android/settings.gradle
- carp_mobile_sensing/example/lib/main.dart
- carp_mobile_sensing/example/lib/trigger_example.dart
- carp_mobile_sensing/lib/domain.g.dart
- carp_mobile_sensing/lib/domain/app_task.dart
- carp_mobile_sensing/lib/domain/data.dart
- carp_mobile_sensing/lib/domain/data_endpoint.dart
- carp_mobile_sensing/lib/domain/device_configurations.dart
- carp_mobile_sensing/lib/domain/sampling_configurations.dart
- carp_mobile_sensing/lib/domain/smartphone_deployment.dart
- carp_mobile_sensing/lib/domain/study_description.dart
- carp_mobile_sensing/lib/domain/study_protocol.dart
- carp_mobile_sensing/lib/domain/tasks.dart
- carp_mobile_sensing/lib/domain/triggers.dart
- carp_mobile_sensing/lib/infrastructure/sampling_packages/device/device_data.dart
- carp_mobile_sensing/lib/infrastructure/sampling_packages/device/device_probes.dart
- carp_mobile_sensing/lib/infrastructure/sampling_packages/sensors.g.dart
- carp_mobile_sensing/lib/infrastructure/sampling_packages/sensors/sensor_data.dart
- carp_mobile_sensing/lib/runtime.g.dart
- carp_mobile_sensing/lib/runtime/app_task_controller.dart
- carp_mobile_sensing/lib/runtime/deployment_controller.dart
* Upgrade to carp_core v. 1.8 & carp_serialization v. 2.0
* Type-safe `fromJson()` methods & nested JSON serialization
* Upgrade of example app to use new Flutter Android Gradle build setup
> 419 upgrade to carp serializable v 20

- backends/carp_backend/lib/carp_data_manager.dart
- backends/carp_backend/lib/data_stream_buffer.dart
- carp_mobile_sensing/example/pubspec.yaml
- carp_mobile_sensing/lib/runtime/executors/executors.dart
- packages/carp_survey_package/CHANGELOG.md
- packages/carp_survey_package/lib/survey_domain.dart
- packages/carp_survey_package/lib/survey_user_task.dart
- packages/carp_survey_package/pubspec.yaml
* upgrading to carp_mobile_sensing v. 1.11
* fix of issue [#342](https://github.com/cph-cachet/carp_studies_app/issues/342)
> carp_survey_package 1.8.1 published

- carp_core/CHANGELOG.md
- carp_core/example/lib/example.dart
- carp_core/lib/common/carp_core_common.g.dart
- carp_core/lib/data/carp_core_data.g.dart
- carp_core/lib/deployment/carp_core_deployment.g.dart
- carp_core/lib/deployment/domain/study_deployment.dart
- carp_core/lib/protocols/carp_core_protocols.g.dart
- carp_core/pubspec.yaml
- carp_core/test/carp_core_kotlin_rpc_test.dart
- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/example/lib/trigger_example.g.dart
- carp_mobile_sensing/lib/carp_mobile_sensing.json.dart
- carp_mobile_sensing/lib/domain.g.dart
- carp_mobile_sensing/lib/domain/triggers.dart
- carp_mobile_sensing/lib/infrastructure/sampling_packages/device.g.dart
- carp_mobile_sensing/lib/infrastructure/sampling_packages/sensors.g.dart
- carp_mobile_sensing/lib/runtime.g.dart
- carp_mobile_sensing/lib/runtime/executors/executor_factory.dart
- carp_mobile_sensing/lib/runtime/executors/task_control_executors.dart
- carp_mobile_sensing/lib/runtime/executors/trigger_executors.dart
- carp_mobile_sensing/lib/runtime/user_tasks.dart
- carp_mobile_sensing/pubspec.yaml
* Support for the `NoUserTaskTrigger` (issue [#453](https://github.com/cph-cachet/carp.sensing-flutter/issues/453))
* fix of issue [#452](https://github.com/cph-cachet/carp.sensing-flutter/issues/452)
> NoUserTaskTrigger & Core update

- packages/carp_movesense_package/CHANGELOG.md
- packages/carp_movesense_package/lib/movesense_device_manager.dart
- packages/carp_movesense_package/lib/movesense_probes.dart
- packages/carp_movesense_package/pubspec.yaml
See [ #378](https://github.com/cph-cachet/carp_studies_app/issues/378)
> Fix of missing serial number

- carp_mobile_sensing/test/cams_domain_test.dart
- packages/carp_health_package/CHANGELOG.md
- packages/carp_health_package/README.md
- packages/carp_health_package/example/lib/example.dart
- packages/carp_health_package/lib/health_domain.dart
- packages/carp_health_package/lib/health_package.dart
- packages/carp_health_package/lib/health_package.g.dart
- packages/carp_health_package/lib/health_probe.dart
- packages/carp_health_package/lib/health_services.dart
- packages/carp_health_package/lib/health_user_task.dart
- packages/carp_health_package/pubspec.yaml
- packages/carp_survey_package/CHANGELOG.md
- packages/carp_survey_package/lib/survey_domain.dart
- packages/carp_survey_package/pubspec.yaml
* upgrading to health v. 12.x
* improving on requesting permissions for different health probes (issue [#461](https://github.com/cph-cachet/carp.sensing-flutter/issues/461))
* added support for `HealthAppTask` which are app task used to collect health data
> Health Package v. 3.0.0

- backends/carp_backend/lib/carp_data_manager.dart
- backends/carp_backend/lib/carp_resource_manager.dart
- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/LICENSE
- carp_mobile_sensing/lib/domain/study_protocol.dart
- carp_mobile_sensing/lib/services/log.dart
- carp_mobile_sensing/pubspec.yaml
- packages/carp_context_package/CHANGELOG.md
- packages/carp_context_package/example/lib/example.dart
- packages/carp_context_package/lib/carp_context_package.dart
- packages/carp_context_package/lib/carp_context_package.g.dart
- packages/carp_context_package/lib/src/context_package.dart
- packages/carp_context_package/lib/src/location/location_configuration.dart
- packages/carp_context_package/lib/src/location/location_data.dart
- packages/carp_context_package/lib/src/location/location_probes.dart
- packages/carp_context_package/lib/src/location_manager.dart
- packages/carp_context_package/lib/src/weather/weather_services.dart
- packages/carp_context_package/pubspec.yaml
> Fix of issues based on sampling coverage analysis

- backends/carp_webservices/CHANGELOG.md
- backends/carp_webservices/example/android/app/build.gradle
- backends/carp_webservices/example/android/build.gradle
- backends/carp_webservices/example/android/settings.gradle
- backends/carp_webservices/example/pubspec.yaml
- backends/carp_webservices/pubspec.yaml
refactor: update Gradle configuration and dependencies for improved compatibility
> Updating gradle and packages

- carp_mobile_sensing/.gitignore
- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/LICENSE
- carp_mobile_sensing/example/.gitignore
- carp_mobile_sensing/example/lib/main.dart
- carp_mobile_sensing/lib/infrastructure/local_notification_controller.dart
- carp_mobile_sensing/pubspec.yaml
- carp_serializable/CHANGELOG.md
- carp_serializable/example/example.g.dart
- carp_serializable/pubspec.yaml
Upgraded and published
- serialazable
- core
- CAMS
> Upgrade core CAMS packages to flutter version 3 29

- carp_core/CHANGELOG.md
- carp_core/lib/common/application/data.dart
- carp_core/lib/common/carp_core_common.g.dart
- carp_core/pubspec.yaml
- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/lib/infrastructure/persistence.dart
- carp_mobile_sensing/lib/runtime/app_task_controller.dart
- carp_mobile_sensing/lib/runtime/client_manager.dart
- carp_mobile_sensing/lib/runtime/executors/deployment_executor.dart
- carp_mobile_sensing/lib/runtime/executors/trigger_executors.dart
- carp_mobile_sensing/lib/runtime/user_tasks.dart
- carp_mobile_sensing/pubspec.yaml
- packages/carp_health_package/lib/health_probe.dart
> Fix of issues with User Tasks

- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/example/lib/example.dart
- carp_mobile_sensing/example/lib/main.dart
- carp_mobile_sensing/lib/domain/data.dart
- carp_mobile_sensing/lib/runtime/user_tasks.dart
- carp_mobile_sensing/pubspec.yaml
- carp_mobile_sensing/test/cams_domain_test.dart
> Sensing and one time sensing merged into one type called sensing

- apps/carp_mobile_sensing_app/lib/main.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/local_study_protocol_manager.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/sensing.dart
- apps/carp_mobile_sensing_app/lib/src/view_models/device_descriptions.dart
- apps/carp_mobile_sensing_app/lib/src/view_models/probe_descriptions.dart
- apps/carp_mobile_sensing_app/pubspec.yaml
- carp_core/CHANGELOG.md
- carp_core/lib/carp_core.json.dart
- carp_core/lib/common/application/devices/device_registration.dart
- carp_core/lib/common/application/devices/heart_rate_device.dart
- carp_core/lib/common/carp_core_common.g.dart
- carp_core/pubspec.yaml
- carp_core/test/carp_core_dart_test.dart
- carp_core/test/json/carp.core-dart/invitations.json
- carp_core/test/json/carp.core-dart/mac_address.json
- carp_mobile_sensing/CHANGELOG.md
- carp_mobile_sensing/lib/infrastructure/sampling_packages/device/device_data.dart
- carp_mobile_sensing/pubspec.yaml
- carp_mobile_sensing/test/cams_domain_test.dart
- carp_mobile_sensing/test/json/measurement.json
- packages/carp_communication_package/CHANGELOG.md
- packages/carp_communication_package/lib/communication.dart
- packages/carp_communication_package/pubspec.yaml
> Macaddress + timezone + telephony fix

- apps/carp_mobile_sensing_app/android/app/build.gradle
- apps/carp_mobile_sensing_app/android/gradle/wrapper/gradle-wrapper.properties
- apps/carp_mobile_sensing_app/android/settings.gradle
- apps/carp_mobile_sensing_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- apps/carp_mobile_sensing_app/ios/Runner/Info.plist
- apps/carp_mobile_sensing_app/lib/main.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/local_study_protocol_manager.dart
- apps/carp_mobile_sensing_app/lib/src/blocs/sensing.dart
- apps/carp_mobile_sensing_app/lib/src/view_models/device_descriptions.dart
- apps/carp_mobile_sensing_app/lib/src/view_models/probe_descriptions.dart
- apps/carp_mobile_sensing_app/pubspec.yaml
Upgrade Gradle and Android plugin versions, update SDK and NDK settings, and modify dependencies for improved functionality. Additionally, enable core library desugaring and register the Cortrium package for enhanced device support.
> Update Android app Gradle and dependencies
